
# ----------------------------------------------------------------------------------------------------------------------
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/culture/locales.c)

# ----------------------------------------------------------------------------------------------------------------------
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/native/mono-native-platform.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/native/pal-icalls.c)

# ----------------------------------------------------------------------------------------------------------------------
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/profiler/helper.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/profiler/aot.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/profiler/log.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/profiler/log-args.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/profiler/proftest-pinvokes.c)

#list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/profiler/vtune.c)
#list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/profiler/mprof-report.c)

# ----------------------------------------------------------------------------------------------------------------------
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-threads.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-threads-coop.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-error.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/atomic.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/bsearch.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/checked-build.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/dlmalloc.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/hazard-pointer.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/json.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/lifo-semaphore.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/lock-free-alloc.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/lock-free-array-queue.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/memfuncs.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-context.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-cgroup.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-codeman.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-conc-hashtable.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-counters.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-dl.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-embed.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-experiments.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-filemap.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-linked-list-set.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-flight-recorder.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-hwcap.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-io-portability.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-internal-hash.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-jemalloc.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-logger.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-log-common.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-math-c.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-md5.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-merp.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-mmap.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-os-mutex.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-networkinterfaces.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-path.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/monobitset.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/parse.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/strenc.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/options.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/networking.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/networking-posix.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/networking-fallback.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/networking-missing.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-utils-debug.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-time.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-uri.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-utility-thread.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-value-hash.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-threads-state-machine.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-threads-mach-helper.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-threads.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-state.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-sha1.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-poll.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-log-flight-recorder.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-proclib.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-property-hash.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-publib.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-signal-handler.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-stdlib.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-tls.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/lock-free-queue.c)

list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mach-support-unknown.c)
list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-hwcap-cross.c)

if (WIN32)
    list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-proclib-windows.c)
    list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/networking-windows.c)
    list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-rand-windows.c)
    list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-windows-thread-name.c)
    list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-threads-windows.c)
    list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/os-event-win32.c)
    list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-mmap-windows.c)
    list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-os-wait-win32.c)
    list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-os-semaphore-win32.c)
    list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-log-windows.c)
    list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-threads-coop.c)
    list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/mono-dl-windows.c)

    list(APPEND MONO_SCRIPT_UTILS_SOURCES ${MONO_SCRIPT_LIBRARY_PATH}/mono/utils/win64.asm)

    list(APPEND MONO_SCRIPT_UTILS_SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/../inc/MonoScript/CPU/cpu-amd64.c)
endif()